### PR TITLE
Handle camera capture devices

### PR DESCRIPTION
**Pull request by simonrw**
If the user supplies something that can be turned into an integer, then they likely want a camera device. This change tries to convert the `video_path` into an integer. If it succeeds then open that device, otherwise leave the video path as suppiled, to open the corresponding file.

### CODE REVIEW

**Comment by Borda** [comment]
Hi, it seems that this repo is inactive for a while... (more than a year :worried:)
Would you consider to pass your changes to this fork https://github.com/Borda/keras-yolo3 ?

**Comment by simonrw** [comment]
@Borda happy to

**Comment by simonrw** [comment]
@Borda turns out your fork does not use opencv which this PR is related to, so no need!

**Comment by Borda** [comment]
If you think that should be included we can add it.. =)

**Pull request closed without merging**
